#debug: true

spring:
  application:
    name: employee-agent

server:
  port: ${SERVER_PORT:8083}

ai:
  a2a:
    server:
      enabled: true


shrija:
  employee:
    ai:
      gemini-api-key:  ${GOOGLE_API_KEY}
      gemini-model: ${EMPLOYEE_GEMINI_MODEL:gemini-3.1-flash-lite}
      mcp-server-url: ${EMPLOYEE_MCP_SERVER_URL:http://localhost:8082}  # was 8072
      attendance-agent-url: ${ATTENDANCE_AGENT_A2A_URL:http://localhost:8084}
      leave-agent-url: ${LEAVE_AGENT_A2A_URL:http://localhost:8087}
      payroll-agent-url: ${PAYROLL_AGENT_A2A_URL:http://localhost:8085}
      manager-agent-url: ${MANAGER_AGENT_A2A_URL:http://localhost:8086}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,beans

logging:
  level:
    com.shrija.employee: INFO
    com.google.adk: INFO
