CREATE DATABASE IF NOT EXISTS hrms_db;

CREATE USER IF NOT EXISTS 'hrms'@'%' IDENTIFIED BY 'hrms123';
ALTER USER 'hrms'@'%' IDENTIFIED BY 'hrms123';
GRANT ALL PRIVILEGES ON hrms_db.* TO 'hrms'@'%';
FLUSH PRIVILEGES;
